### ISSUE TITLE
Ability to delete a review

### ISSUE THREAD

**Issue by mglax** [dpc/crev#104]
So I was messing around with `cargo-crev` and I ended up reviewing the same crate (`bigint`) twice. So now, I have this:

    flagged   2  2    17700     91937 0/2 bigint               4.4.1 

I think a command should be provided for a user to delete his own reviews

**Comment by dpc** [comment]
Yeah. I'd like to have it.

Right now you can just point your text editor to on of the files in ~/.config/crev/proofs/*` and just delete it. Proof Repository is just a normal git repository with text files.

**Comment by dpc** [comment]
Also, newer reviews are supposed to overwrite older ones, so technically there's no need to remove old ones.

**Comment by dpc** [comment]
@mglax I've landed code it master, that implements the review being overwritten. All the counts and listings should not use the old review of the same package. Please double check if you can. :)

**Comment by mglax** [comment]
Seems like it's working

**Comment by dpc** [comment]
Before I close this: when writing a review for crate version that was already reviewed, maybe we should start from the content of the previous review?

**Comment by bwbroersma** [comment]
> when writing a review for crate version that was already reviewed, maybe we should start from the content of the previous review?

Are you only talking about your own reviews or also reviews by others? Since I think reviews are only really meaningful if you understand/reviewed the complete crate, independent seemingly harmless partial reviewed commits/versions can create a malicious update in the end.

**Comment by dpc** [comment]
Whatever is decided, it should be implemented in #113

**Comment by dpc** [comment]
Moved to #113
