### ISSUE TITLE
Load existing id

### ISSUE THREAD

**Issue by ThomasdenH** [dpc/crev#115]
Instead of creating a new id, it should be possible to load an existing id. The ideal workflow would be one command that accepts an existing git repository and then entering one's details.

**Comment by dpc** [comment]
I was thinking about having `crev export id` and `crev import id` that would print/take `LockedId` ons stdout/stdin. Right now it is possible to do it manually by copying file from `~/.config/crev/ids` and then `cargo crev switch id <copiedid>`, and `cargo crev pull`.

**Comment by dpc** [comment]
The `LockedId` is where the stuff like encrypted private key is stored. Given a strong enough passphrased, it could probably be stored right in the git repo, but I am not sure how good of an idea this is, security-wise.

**Comment by dpc** [comment]
@ThomasdenH Please test. :)
