### ISSUE TITLE
Parsing of $VISUAL with spaces

### ISSUE THREAD

**Issue by kornelski** [dpc/crev#120]
> Error: Couldn't start the editor: "/Applications/Sublime
>  caused by: No such file or directory (os error 2)

That's because path to my editor contains spaces and extra arguments:

```sh
$ echo $VISUAL
"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" -w
```

**Comment by rffrancon** [comment]
A similar issue has just been fixed and closed: https://github.com/dpc/crev/issues/119

Are you sure you're using the latest commit?

**Comment by kornelski** [comment]
I am using the latest. #119 broke it too, just in a different way.

`VISUAL` is neither a command path, nor a path split on spaces. It's a template for a shell script. It's not compatible with the way Rust's `Command` works, unfortunately.

```rust
Command::new("/bin/sh").arg("-c").arg(format!("{} {}", visual, shell_escape(path)))
```

**Comment by dpc** [comment]
Oh dear.

**Comment by dpc** [comment]
I would appreciate someone reviewing and testing it again. I've tested it briefly.

**Comment by dpc** [comment]
269c8461ad673ca109db16833cdf772882a9ba6d

**Comment by kpcyrd** [comment]
I've looked into implementations of `$VISUAL` recently and the common way this is implemented is:
```rust
Command::new(visual).arg("--").arg(path)
```

**Comment by dpc** [comment]
https://doc.rust-lang.org/std/process/struct.Command.html says "where program gives a path to the program to be executed". If it is supposed to support shell commands, then it has to `/bin/sh` etc. Though maybe we should add `--` somewhere? I'm not sure. Is anyone successful in finding a documentation for how it is supposed to work? :D

**Comment by dpc** [comment]
Oh dear. How will `/bin/sh` work on Windows?

**Comment by dpc** [comment]
I did something basic for Windows for now.

**Comment by kornelski** [comment]
Thanks. It works for me now.
