### ISSUE TITLE
Add `cargo crev review --current`

### ISSUE THREAD

**Issue by kornelski** [dpc/crev#121]
If I've made a crate, I can say I have fully reviewed it, and fully understand it.

It would be helpful if there was a shortcut/template for making a positive review of one's own crates.

```sh
cargo crev review --own
```

or something like this, that reads crate name from `./Cargo.toml`, opens a review template with appropriate defaults.

**Comment by dpc** [comment]
You mean review of the current crate your are in the root of right now? This might be tricky, because how can `crev` be sure that what you are having there, is really the same as what `cargo` has?

You can definitely do `cargo crev review --independent <name> <version>`, after you `cargo publish`. 

Generally, it is best if users do `cargo crev goto --independent <crate>` and review the actual files that `cargo` has downloaded, to make sure no tampering was taking place. 

What do you think?

**Comment by kornelski** [comment]
Sure, after publishing is fine too. 

My request was in general about quicker workflow for reviewing my own crates — I trust myself, so I'd like to generate "I trust myself" reviews for all my crates, as easily as possible.

**Comment by dpc** [comment]
Would `cargo goto --current`, jumping to the published&downloaded source of the crate information taken from the cwd `Cargo.toml` be OK? Then inside you could check if it looks OK, and do `cargo crev review`.

**Comment by kornelski** [comment]
Yes, that would improve one part.

The second part is that `cargo crev review` should default to trust = `high` and thoroug = `high`.

**Comment by dpc** [comment]
OK. Let's do it! Marked as "to be done soon". How soon is not specified though. :D

**Comment by Bert-Proesmans** [comment]
Why `current` as an optional parameter?

`cargo goto --current`
VS
`cargo goto current`

The latter should be correct syntax, but i understand that it might clash with a crate that's named with the same word. Thoughts?

**Comment by kornelski** [comment]
I've attempted reviewing my crates via `cargo crev review --independent $name`, and:

* Having to "Enter passphrase to unlock" each time for every single one of them was tiring. That's probably the biggest pain point. 
   * Could cargo-crev remember the pass-phrase for longer?
   * Maybe there could be a multi-crate batch-mode? (`cargo crev review --independent $name1 $name2 $name3`)

* The change from "low" to "high" for every one of them is a little chore, as I've mentioned

* Directories on disk weren't as useful as I hoped, and `--current` or `--path .` wouldn't be that great actually. I ended up checking my profile on crates.io

* I have published some things that I actually wouldn't recommend (e.g sys crates for code that isn't mine)

So here's another idea:

     cargo crev review all the stuff I published

1. Ask for passphrase once
2. Download the list of all crates owned me on crates.io
3. For each crate as if it's good or bad
4. Profit!

**Comment by dpc** [comment]
I don't know if I want this. I mean - did you **really** review the source code and made sure crates.io did not add some fishy stuff? I am quite sure they didn't, but the whole point is to make sure. :)

So, while it's tempting to mass-review a lot of stuff, especially now, that it seems like there's hundreds of thousands of crates that require a stamp of approval, I fear that mass-reviews are actually compromising on the primary function - having someone look through the code.

**Comment by dpc** [comment]
@kornelski I was looking at this thread again.

> The change from "low" to "high" for every one of them is a little chore, as I've mentioned

I've created #138 to address it. At very list you could use shell history, to help, when reviewing crate by crate.

> Could cargo-crev remember the pass-phrase for longer?

We would probably need some form of agent for this. This would probably solve itself if a GPG was implemented, and used as an id.

> Directories on disk weren't as useful as I hoped

Can you elaborate? I am a Vim/kakoune user so for me `cargo crev goto` is all I need.

But i hoped, maybe `cargo crev open <crate>` with an user-defined  command would be useful to help people open the source code as a project IDE or something.

I'm trying to figure how do people actually want to review crates, and make it as convenient for them as possible.

**Comment by kornelski** [comment]
Args for defaults are a nice idea.

`open` command will be useful too, as I would definitely like viewing the crate in Sublime.

GPG is interesting. I'd be interested in leveraging GitHub's support for GPG-signed commits, since that's a reasonably easy to manage identity.

**Comment by Nemo157** [comment]
> I don't know if I want this. I mean - did you really review the source code and made sure crates.io did not add some fishy stuff? I am quite sure they didn't, but the whole point is to make sure. :)

Maybe `cargo-crev` could give a quick way to generate a package from the current working directory, then pull the corresponding package from crates.io and show a diff, so you can easily review whether crates.io modified it.

**Comment by kornelski** [comment]
Closing, since mass-reviewing is fraught with problems, and crev has a concept of trusted users now.
