### ISSUE TITLE
Windows paths could be improved.

### ISSUE THREAD

**Issue by daxpedda** [dpc/crev#125]
Currently on Windows the paths used by crev look like this: `X:\Users\<Username>\AppData\Local\Dawid Ci,281,,380,arkiewicz\crev\remotes`.

My proposition is to remove the `Dawid Ci,281,,380,arkiewicz` part entirely.
Going to make a PR for it.

**Comment by dpc** [comment]
@daxpedda Agreed. Thank you for checking it!
