### ISSUE TITLE
Start maintaining CHANGELOG.md

### ISSUE THREAD

**Issue by dpc** [dpc/crev#134]
document some biggest changes since last version:

* [ ] README handling
* [ ] change of paths on Windows and MacOS

**Comment by dpc** [comment]
@daxpedda :)

**Comment by Dylan-DPC** [comment]
Instead of maintaining a seperate changelog file, i prefer to mention all the changes in github releases and we can think of using [this](https://github.com/dpc/crev/releases) as a changelog.

**Comment by dpc** [comment]
How do you remember what were the changes? :) @Dylan-DPC . Reviewing `git log` is not great. :) . When releasing, I would just like to copy-paste stuff from `CHANGELOG.md`, and keep maintaining it as things are being worked on.

**Comment by Dylan-DPC** [comment]
> How do you remember what were the changes?

We add a "relnotes" or "release notes" label on the PRs we want to mention in the release notes. Then when writing them out filter by that label and write them out briefly in the changelog.

**Comment by dpc** [comment]
>  We add a "relnotes" or "release notes" label on the PRs we want to mention in the release notes. 

Makes sense. 

@kpcyrd - this is #130 related. Any opinions?

**Comment by dpc** [comment]
@Dylan-DPC If you'd like to be responsible for it, then you're free to do it the way you like it best. :)

You probably want to modify the PR github template with some instructions.

Thank you everyone!
