### ISSUE TITLE
`lanes` are not saved in the LockedId configuration

### ISSUE THREAD

**Issue by dpc** [dpc/crev#151]
## Workaround for people who were pointed here by the link

Locate your `LockedId` file. On Linux it would be something like `~/.config/crev/ids/8iUv_SPgsAQ4paabLfs1D9tIptMnuSRZ344_M-6m9RE.yaml`

Locate `pass` section. Add the `lanes`  field:

```
  memory-size: 4096
  salt: someDigitgits
  lanes: N
```

where `N` is the number from the warning **on a computer you originally generated your ID**. This number is number of CPU cores, so you can guess it ito.

## Problem description

If you export and import your id on a computer with different number of CPU, your password won't work.

Lame of me. I thought `lanes` does not change the end hash.

**Comment by dpc** [comment]
I've pushed a fix that should generate correct file, and will warn when using old buggy configuration.

**Comment by kornelski** [comment]
I have this problem, but the fix doesn't work for me. My Id already contains `lanes: 4`.

I haven't moved the key, but I've upgraded my CPU. I've tried putting current number of cores/threads, but crev just keeps saying it's not configured.
