### ISSUE TITLE
Rename `--indepdented`

### ISSUE THREAD

**Issue by dpc** [dpc/crev#155]
`--independent` is such a pain to type. I think it's also confusing. Anyone for bikesheding a better name?

The meaning is: Most of the time reviewed crates are the dependencies, which makes it easy for `crev` to auto-guess the version, etc. But sometimes we want to do something for a crate that is not a dependency of a current project.

* `--unrelated`
* `--nodep`
* `--global`

**Comment by kornelski** [comment]
Does the flag even have to exist?

I'd say if it's in a project, use that project's version, otherwise use latest.

**Comment by dpc** [comment]
I'm afraid of typos and typo-squatting. Also, accidental version mismatch. The good part of limiting set of crates to deps is that `name` usually uniquely identifies both name and version, and gives plenty of room for detecting typos.

Right now I am leaning toward `--unrelated` and `-u`.

**Comment by kornelski** [comment]
But if you review the code, and cargo-crev attributes it to the right crate, is getting the wrong name any vulnerability?
