### ISSUE TITLE
Fight for survival.

### ISSUE THREAD

**Issue by dpc** [dpc/crev#164]
Let's face the truth: after an initial wave of enthusiasm, noone is using `crev`. :D

Time to kickstart it a bit.

First: it has to be become more useful even for "leachers" (people who are not planing to review stuff themselves, but just want to get some help).

* We need the summary view to be as useful as possible from the start - without reviewing anything.

* We need a bot that translates security advisories into crev proofs under a know CrevID. That's a free source of useful information that is easy for everyone to follow.

* We need an ability to "mark all previous versions as insecure" to efficiently mark fixed security voulns.

* We need to release geiger changes, after dalek library problems are sorted out. https://github.com/dalek-cryptography/ed25519-dalek/issues/75

* After all of this is done, it's time for more advertising and spamming.

**Comment by andrewchambers** [comment]
I think the most logical way is to target languages with the most users and vulnerabilities e.g. npm.

I think a second way would be to simplify the design, I question the need for keys and signing when we have https on git urls.

Finally, a third way is to deliver high quality reviews. People are eager to have reviewed code, not to review it themselves. I really think paying people for reviewed code is the right way to go, but I'm less sure how to make this happen.

**Comment by kofalt** [comment]
Apologies in advance if this comment is unwelcome, unhelpful, or out of date. I love the idea of this project and would be excited to see wider adoption.

From an increasing-enthusiasm perspective, I am a current non-user of crev and I'm interested in changing that. When I came upon this project awhile back, the concept appealed to me, but from a (possibly faulty) perusal of the readme and wiki, it wasn't clear how best to produce or consume reviews for non-rust repositories. This lead me to "watch" the repo and wait to see what changed :)

You would gain 1 (or more!) users if there were clear, 2-minute instructions showing how to get started using crev by reviewing a language-agnostic clone URL, then how find reviews for that same URL. This would be more than enough to jury-rig crev into $PackageManagerFileFormat with a little bash or python scripting.

With something like that available, I would happily maintain a repo of a few reviews of Golang libraries that I use regularly, and write + share a simple script that would check your added review sources against libraries you have imported in [glide.sh](https://glide.sh) (arguably the most popular Golang manager) and the newer, standard-library Golang package format.

**Comment by dpc** [comment]
@kofalt There is currently no frontend for languages other than Rust. While crev can be used for any source code, for it to be useful to work with, it has to be somewhat integrated with a package manager / build system / etc. Right now I'm working on `cargo-crev`, which is integration with Rust's `cargo`. I welcome anyone that would like to work on any other frontend, but I personally have no time to do it myself.

**Comment by dpc** [comment]
The amount of reported security issues for Rust is so low, that after #163 is implemented, I can just create proofs for everything manually, and publish in my repo. Seems good enough.

**Comment by andrewchambers** [comment]
@dpc My concern with rust is more that someone will inject some malware into a transitive dependency that gets cargo published without review, then the update gets pulled without review.

**Comment by dpc** [comment]
@andrewchambers I'm not sure how to respond. `cargo-crev` lists and checks all the dependencies, recursively. In a perfect world any new release gets couple of quick reviews by the community, and everbody else can consider it safe to use.

**Comment by andrewchambers** [comment]
@dpc Sorry my comment wasn't too clear. I basically meant as a user, the only thing I care about is "green" or "red". There are lots of other features in cargo crev and I was getting confused by them. It was just some feedback, though maybe bad feedback. I will try a second time to use crev, but the first time I gave up quite easily.

**Comment by andrewchambers** [comment]
@kofalt I made the same mistake as you, thinking crev was a stand alone tool and that cargo crev was a plugin that uses crev.

**Comment by kofalt** [comment]
Based on @dpc's comment it sounds like it could become fairly stand-alone if the way to interact with crev is friendly enough to external tooling. I personally would get mileage out of something like crev without any package manager integration at all. The simpler it is to plug into other tooling, the better!

**Comment by dpc** [comment]
@kofalt There is a `crev-bin` project that compiles to standalone binary. It was supposed to be used mostly inside repositories of standalone project to review parts of source code. I have just stopped working on this approach, and focused on reviewing whole packages of a given ecosystem (Rust/crates.io).

**Comment by dpc** [comment]
Done.
