### ISSUE TITLE
Website to see available reviews?

### ISSUE THREAD

**Issue by GuillaumeGomez** [dpc/crev#168]
Being able to look through all the projects and their reviews would be really useful! Do you consider adding one?

**Comment by dpc** [comment]
UI would be a lot of work, but https://github.com/dpc/crev/wiki/List-of-Proof-Repositories is basically a list of known repos, and you can click any, and then in couple of clicks, start reading: https://framagit.org/antoyo/crev-proofs/blob/master/YprNWjWf_8ujZPxwE6eR0G9mLwVpdU4fgo5IrygEmuY/reviews/2018-12-packages.proof.crev

Part of the reason why crev uses yaml, is that it's easily readable without any tools.
