### ISSUE TITLE
Weighing opinions of reviewers

### ISSUE THREAD

**Issue by matthieu-m** [dpc/crev#20]
One issue of any review system, is that not all reviewers are created equal:

 - some are more knowledgeable in certain domains,
 - some have (possibly unconscious) bias,
 - some may have agendas (zealots),
 - ...

It can be difficult enough to weigh in the opinion of multiple reviews when one personally knows the reviewers; when they are anonymous and numerous, such as in crev, it is just unwieldy. And unfortunately the "average" only gets you the opinion of the masses, which risks drowning the voices of the experts in the noise.

I have been thinking hard about this problem of scaling trust from a handful of individuals to an unlimited number of them, and my answer is to trust a few *founders*, and let them delegate (part of) their authority in a hierarchical Web of Trust. Then, associating a weigh to a handful of webs seems like "reasonable" homework, and more casual users can just go with the community consensus.

I have described the system, at length, at [Scaling Trust: Weighted Webs of Trust](https://github.com/matthieu-m/matthieu-m.github.io/blob/master/wwot.md). It is relatively complete, as far as I can see, and should support this goal in a scalable way.

The one remaining question, however, is how susceptible the system is to malign individuals. That is, how easy it would be for a determined individual, or group, to subvert the system? I have already tried to imagine multiple attack vectors, their consequences, and the available mitigations and responses... however it only takes one vulnerability to upend all this, so I would appreciate additional eyes.

**Comment by dpc** [comment]
While interesting, this system is like two orders of magnitude more difficult than what I'm aiming at right now.

Some accommodations maybe could be made for `crev` to be compatible etc. but right now there's nothing actionable there, so I am closing the issue.
