### ISSUE TITLE
Too many deep subcommands

### ISSUE THREAD

**Issue by kornelski** [dpc/crev#218]
Re #211

> cargo crev query id own

Not counting cargo, that's 3 levels of subcommands deep! I've noticed that crev uses subcommands to form sentences. That doesn't work too well with clap, because clap gives info only about 1 level at a time, so finding "query id own" requires:

> cargo crev --help
> cargo crev query --help
> cargo crev query id --help

and each level gives just a brief mention.

I suggest flattening the hierarchy, and reversing the order. Commands that manipulate own ID could all be grouped together:

```
cargo crev id new
cargo crev id export
cargo crev id import
cargo crev id show
cargo crev id switch
```

There are also a few verbs at the top level, which I think are just different starting templates for reviewing.

```
cargo crev review --advise
cargo crev review --report
cargo crev review --flag
```

**Comment by dpc** [comment]
You can do `cargo crev id help` BTW. No need to `--` in most cases.

I'm unsure about this, though I'm open for discussion.

`cargo crev query id own` would turn into ... ? ... `cargo crev id query own` ? Is that any improvement? Or if `own` becomes `--own`?

Is the thing here, only about improving discoverability of `crev <object> <action> <qualifiers>` over `crev <action> <object> <qualifiers>`?

I wish `clap` could just print help recursively, like 2 levels deep, to flatten the discoverity.


> There are also a few verbs at the top level, which I think are just different starting templates for reviewing.

Indeed. However `review` already supports `--issue` and `--advisory`.

**Comment by kornelski** [comment]
I assume `cargo crev id …` is for managing your own id only, so `own` is redundant. `cargo crev id` could be the only thing you need to display your own IDs.

**Comment by dpc** [comment]
>  (although I'm not suggesting to take too much from Git's UI :))

Git UI is ... terribly inconsistent. :D . `git checkout`, `git pull` etc. suggest preference of `git <verb>`. Even `stash` is (I guess) a verb, and `save` and `pop` are kind of qualifiers?

> is for managing your own id only

What about other ids-related queries? I could make `cargo crev query id` an alias and thus have both `cargo crev query id own` and `cargo crev id query`, but then number of supported command and their aliases will get even larger, and the benefit of easier way to accomplish the most command things.

**Comment by kornelski** [comment]
I guess the `query` one is a special kind of database interface ("plumbing" in git-speak), so that's fine to stay as is.

**Comment by kornelski** [comment]
I've created #219
