### ISSUE TITLE
Combine push/pull subcommands

### ISSUE THREAD

**Issue by kornelski** [dpc/crev#220]
To reduce number of commands, some further improvements:

- combine `fetch` `pull` and `update` into one `update` that optionally takes arg to fetch only a specific thing. By default fetches/updates everything. The assumption here is that there's nothing good in having an outdated state (and relying on having outdated state is fragile). Most of the time you want them all up to date, and it's easier to run 1 command than 3.

- combine `push` and `publish`. There's `git` subcommand for fine-grained management, but by default it could act as a simple sync.

**Comment by dpc** [comment]
AFAIR, `publish` is already doing `pull --rebase` + `push`, and for a while now I don't remember using anything else. I should probably get rid of the other ones, as they are not terribly useful, and can always be achived by using `git <args>`
