### ISSUE TITLE
Key file world-readable by default?

### ISSUE THREAD

**Issue by icefoxen** [dpc/crev#226]
Just double-checking, because the answer isn't entirely clear.  `crev` creates my ID key file in `~/.config/crev/ids/<public key>.yaml` as world-readable by default, so anyone else on my system can see it.  Is this okay?  Do I need to make sure that my backups of it are encrypted?  It LOOKS like the private key portion of the file is encrypted already and thus the file is useless without my passphrase, but I feel obligated to double-check.  Thanks in advance!

 * Which version are you using: crev 0.8.3
 * How did you install `crev`: `cargo install cargo-crev`
 * What OS/platform are you running on: Linux, Debian 10 Stable

**Comment by dpc** [comment]
The key file is encrypted with the passphrase which is key-stretched, and quite strongly hashed to be brute-force resistant, but I agree that it would be better to just make the key file readable only to owner. Good catch!
