### ISSUE TITLE
Contributing/Technical documentation

### ISSUE THREAD

**Issue by tylerlaberge** [dpc/crev#23]
It would be awesome if you could add a CONTRIBUTING.md and/or some documentation on the more technical side. Doesn't need to be much since this is still early and sure to change, but some notes on where everything is/how the code is organized could make it easier for others to contribute :)

**Comment by Dylan-DPC** [comment]
Thanks @tylerlaberge 

A sketch of the concept is available [here](https://github.com/dpc/crev/wiki/cargo-trust:-Concept)

**Comment by dpc** [comment]
I have added a `HACKING.md` file. It will have to do for now. :)
