### ISSUE TITLE
cargo trust potential design issues

### ISSUE THREAD

**Issue by Ekleog** [dpc/crev#24]
Hello,

I have just come upon https://github.com/dpc/crev/wiki/cargo-trust:-Concept ; and have a few comments about it.

First, ~`$ cargo trust verify`~ `$ cargo trust project` (EDIT: oops) appears to trigger `Updating registry`. This means that somehow, signing something triggers a download. If it does, then how do I know that what I'm signing is what I have reviewed? It should definitely not need to download anything, as if it needs to then there's a TOCTOU attack.

Second, `trust project` and `trust id` are under the same subcommand. This is one of the design errors of GnuPG (and in a way OpenPGP): putting ownertrust and key validity under the term “sign”. Here, you want to consider project's validity, and other key's trust. As such, I don't think it makes sense to jam the two under the same command, and it will likely lead to the same kind of confusion brought by GnuPG's interface and everyone confusing ownertrust and key validity. Maybe `validate project` and `trust id` would be better names.

Finally, one of the big drawbacks of reimplementing one's own crypto (by having one's own keypair) is that it means it can't be put on a secure hardware token (eg. smartcard). Which is not nice from a security point of view, if you assume that identities are supposed to survive computer compromise.

HTH,
Leo

**Comment by dpc** [comment]
`cargo trust verify` is verifying dependencies of the project. So it must download them first to the version specified in `Cargo.toml`/`Cargo.lock`. A command to set trust is actually `cargo trust project <projectname> [<version>]`.

Please note that `cargo trust` is actually "one command" designating cargo subcommand `cargo-trust`. It doesn't mean "trust" verb. It means call `cargo-trust` tool (noun).

I think it creates a lot of confusion. Originally it was supposed to be named `cargo crev`, but I thought it's going to integrate better if it's named `cargo-trust`.

So do you think it would be OK if the mention commands were:

```
cargo crev verify - verify current project and it's depdendencies
cargo crev trust id <id> - trust <id>
cargo crev trust project <project_name> [<project_version>] - trust code that you've just reviewed
```

> Finally, one of the big drawbacks of reimplementing one's own crypto (by having one's own keypair) 

The design is open for adding gpg and other identities later, hardware keys included. I use hardware gpg with yubikeys myself, so I want this. But it's both easier for most potential users, and for the purpose of initial release to start with own keys. Not to mention GPG hardware keys have terrible UX and many problems and bugs...

**Comment by Ekleog** [comment]
Oops, I wrote `$ cargo trust verify` while thinking `$ cargo trust project`. Sorry for the confusion! So my point stands only for `cargo trust project` :)

As for the names, I think the alternative version you propose still has this re-use of `trust` for both owner-trust with `trust id` (trusting someone to do reviews) and for project-validity (verifying a project's code is legitimate). I've just been pointed to [the reddit post](https://www.reddit.com/r/rust/comments/a1a0t9/if_you_want_to_prevent_package_hijacking_come/), the topmost comment's is, I think, a good example of confusion similar to GnuPG's that I was pointing out.

So I think
```
cargo crev verify
cargo crev trust <id>
cargo crev validate <project_name> [<project_version>]
```
would be a better UI :) (note: I don't really understand what `cargo crev validate` without `project_version` is supposed to accomplish)

**Comment by dpc** [comment]
Oh, I see. I'm not sold on `validate` but I get your point. What's so wrong with reusing `trust` for both `id` and `project`? In both cases you want to show that you're trusting either the project in the state you've inspected it, or the user-id that you've found. 

> I don't really understand what cargo crev validate without project_version is supposed to accomplish

It can auto-detect the version you're using for your convenience.

**Comment by Ekleog** [comment]
> What's so wrong with reusing trust for both id and project? In both cases you want to show that you're trusting either the project in the state you've inspected it, or the user-id that you've found.

Well, the thing is that:
 * Trusting a project is an intransitive notion: I have reviewed this project, and that's all
 * Trusting an user is a transitive notion: I have reviewed this user's signing policy, *and* trust them to follow it, *and* will automatically “trust” all projects they “trust” (plus questions about transitive trust and whether if I trust you who trusts person C and person C “trusts” a project, do I “trust” it? but that's a marginal question)

I'm not really sold on the `validate` keyword choice, but I think it's very important that the two not be the same word. On GnuPG's ML a surprisingly big portion of support requests come from a misunderstanding of “signing a key” vs. “assigning ownertrust to a key”, because at some point the wording of GnuPG was the same and many tutorials or other docs on the internet kept the old wording since then.

> It can auto-detect the version you're using for your convenience.

If there are multiple versions in the crate graph, does it bail out? Also, I'd personally think that the risk of confusion (“this is trusting the whole project and all future versions”) is greater than the benefit of convenience, given that anyway one would already have reviewed the project, which is a much more daunting task than adding a version number on the command line.

**Comment by Ekleog** [comment]
>> this is trusting the whole project and all future versions
>
> If it was confusion in the other direction ("I thought I'm trusting this one version, but I trusted the whole thing" then I would be worried). This direction not so much. It's quite rare to have multiple versions anyway, and the whole workflow makes it quite clear that one is working on the directories of particular releases. But I'll keep it in mind.

Indeed, it's not really a security issue, more an issue of people
wondering what is going on and coming to the issue tracker / gitter /
mailing list with an endless stream of questions :)

**Comment by Ekleog** [comment]
> The way you wrote it suggest it should be `trust <userid>` and `review <project>`.

SGTM. The reason I originally avoided `review` is that the term is kind
of used everywhere for different meanings, but I don't think I have a
better solution indeed :)

**Comment by dpc** [comment]
I agree, and will make it happen. Closing for now. Thanks for pointing it out!
