### ISSUE TITLE
`ed25519-dalek`, `miscreant`, and other crypto - stabilize

### ISSUE THREAD

**Issue by dpc** [dpc/crev#32]
`ed25519-dalek`, `miscreant` are both in pre-final release.

`ed25519-dalek` is almost 1.0.0 but other crypto libraries are not. Is it a bad idea to use them?

When it's OK to release `crev` to the public?

**Comment by Dylan-DPC** [comment]
I think it is fine if a dependency hasn't reached 1.0. The more important question is whether the dependency has been audited for security.

**Comment by dpc** [comment]
Both `ed25519-dalek`, `miscreant` seem to have competent teams behind them, but yeah... it will have to be double check, maybe discussed with them.

A different library could be used, but these two looked promising, and I was just rushing to get something working. :)

**Comment by dpc** [comment]
I pinged people on both teams

**Comment by dpc** [comment]
https://github.com/dalek-cryptography/ed25519-dalek/issues/69

**Comment by dpc** [comment]
https://github.com/miscreant/miscreant.rs/issues/8

**Comment by dpc** [comment]
Not much to do here, and once ed25519-dalek has 1.0.0, we will just update.
