### ISSUE TITLE
Review recursive digest crate.

### ISSUE THREAD

**Issue by dpc** [dpc/crev#42]
`cargo crev` is using a custom recursive digest algorithm to calculate the unique digest of the crate content. It is vitally important that this operation is cryptographically secure, and there are no bugs, so it doesn't have to get fixed while all previously calculated and signed digests are now incorrect.

I'd like at least one person go through that fairly small sub-crate and reviewe it.

**Comment by oberien** [comment]
Is there a reason you aren't just using a merkle tree? Merkle trees are an established way to generate a unique signature for a file free. That way you won't have to roll your own algorithm, which would need to be reviewed. Instead only your implementation of the merkle tree would need to be reviewed.

**Comment by dpc** [comment]
@oberien Any existing implementations of merkle tree used for file system directory?

The way I see it merkle tree is OK for a set. Then it's easy and proof of inclusion is useful. Here it's an directory, and any proof of inclusion will typically involve a whole sub-directory or something, which in case of my construction can be done much more efficient.

The construction that I've implemented can be thought of spin-of and a super-set of merkle tree, in a similiar way that b-tree is a to binary tree. It just works so much easier for directory structure, that by nature has N instead of just 2 children.

**Comment by dpc** [comment]
I am actually quite convinced that the construction itself is solid, because it's simple and should be self-evidently correct. What I'm worried are lame implementation bugs.

**Comment by dpc** [comment]
I need to implement a simple `md5sum`-like binary on top of the recursive tree library I have, and maybe write myself another implementation ... maybe in Python or something, just to make sure they give the same result.

**Comment by oberien** [comment]
Could you please roughly outline your attacker model? What are the consequences of a forged hash for a single file / symlink / a full directory / the toplevel hash for the whole crate?

After taking a look at the general concept, I saw that you're basically using the directory entry type as a salt for the hash. By only prepending that salt, you can't use hashes which are susceptible to length extension attacks and have a known second preimage vulnerability like SHA1 and MD5. Using an HMAC here would resolve this issue and allow even a secure use of MD5 as the digest.

**Comment by dpc** [comment]
@oberien I just need digest of a given file system path to be uniquely identify it's content. It should not be forgeable, the same way as a simple cryptographic hash function should uniquely identify a bigger file. My use case is `crev` where this hash will be used make sure Rust/cargo package content wasn't tempered with, but the library should be general purpose.

I like that my algorithm takes one existing hash functions, and just runs it multiple times recursively. (Similar to eg. https://www.youtube.com/watch?v=Dya9c2DXMqQ) I would like to avoid adding any other "input parameters/functions". I don't think I need to try to fix weak hashes. If you give it a weak hash, you get a weakened recursive hash. Garbage in-garbage out. I `crev` I'm going to use it with blake2b, and truncate the output to 256bits of security.

BTW. I really appreciate you looking at it. Please let me know if you disagree with anything.

**Comment by dpc** [comment]
Well, the ship has sailed. :D
