### ISSUE TITLE
`List` commands

### ISSUE THREAD

**Issue by dpc** [dpc/crev#47]
```
cargo crev
  list
    ids all # all known
    ids trusted
    ids mine # currently `id list`
    reviews <package_name> <package_version>
```

**Comment by dpc** [comment]
`ids mie` or `ids own`?

**Comment by rffrancon** [comment]
I'm not certain if a `list` subcommand is a good idea. Consider the `git remote` subcommand. This subcommand has a further subcommand called `show`. In git the subcommands seem to be organized for the most efficient division of the name space.

Crev already contains an `id` subcommand. Perhaps that subcommand can be extended with `crev id show`. And then:
* `crev id show --trusted`
* `crev id show --own`

(With the default being equivalent to `crev id show --all`).

**Comment by dpc** [comment]
@rffrancon Yeah. So I'm not certain how to structure the commands. There are many combinations of nons and verbs that make sense.

Having it `cargo crev list` groups them together by functionality: "looking up information in the proof database".. I thought about `cargo crev id` as "managing your own ids".

I am all open for suggestions. :)

**Comment by dpc** [comment]
> git remote add {remote_name}).

Then, you have `git push`, `git pull`, etc. These are basic operations, they are common so they are pulled to the root.

There will a lot of weird things that user might want to look-up. I was planing to dump more and more stuff under `list` (which I now think abound renaming to `search` or `find`, or ... `query`... or something, maybe even noun). 

* "give me all reviews for a given package"
* "give me all packages that have newer version that I could trust"
* "give me all users that I almost trust, but not quite yet"

* etc.

The way I think about it is:

```
<tool> <category> <arguments>
<tool> <very-common-operation>
```

As long it is easy to type and discover then I don't really about consistency. 

Also, I wouldn't worry too much about it, because we can change it later.

**Comment by dpc** [comment]
I also think about removing `db` prefix altogether. It's painful to type, and pretty much everything is about the "database of proofs" here, so what's there's not a lot of point.

**Comment by dpc** [comment]
Now that I think about it the `cargo crev <verb> <object>` might work ...

I'll move this to another issue.

**Comment by rffrancon** [comment]
> > git remote add {remote_name}).
> 
> Then, you have `git push`, `git pull`, etc. These are basic operations, they are common so they are pulled to the root.
> 
> There will a lot of weird things that user might want to look-up. I was planing to dump more and more stuff under `list` (which I now think abound renaming to `search` or `find`, or ... `query`... or something, maybe even noun).
> 
>     * "give me all reviews for a given package"
> 
>     * "give me all packages that have newer version that I could trust"
> 
>     * "give me all users that I almost trust, but not quite yet"
> 
>     * etc.
> 
> 
> The way I think about it is:
> 
> ```
> <tool> <category> <arguments>
> <tool> <very-common-operation>
> ```
> 
> As long it is easy to type and discover then I don't really about consistency.
> 
> Also, I wouldn't worry too much about it, because we can change it later.

I see your logic now! Everything you've said makes sense to me.
