### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by dpc** [dpc/crev#52]
I'm planing to migrate to:

```
license = "MPL-2.0 OR MIT OR Apache-2.0"
```
everywhere. Just to give people more choice. I did in digest crates already, before releasing.

 @Dylan-DPC @rffrancon . Ack? :)

**Comment by Dylan-DPC** [comment]
do we need to triple license it? i think `MIT or Apache-2.0` is enough given how widely it is used in the rust community.

**Comment by dpc** [comment]
MPL-2 is my favorite, and it doesn't hurt to just have them all ORed. That works as anyone can pick the one that fits them best.

**Comment by rffrancon** [comment]
ACK, from my point of view, the more options the better. :)

**Comment by zachaysan** [comment]
This is great, but you should make a LICENSE file explicitly so people looking at the project can see it. Or at least add it to the README.

**Comment by Bert-Proesmans** [comment]
A LICENCE file is best. Github parses the file to give a quick overview of rights and obligations, as well as tagging the entire repo with the licence.
