### ISSUE TITLE
How should commands be structured?

### ISSUE THREAD

**Issue by dpc** [dpc/crev#53]
Moving discussion from https://github.com/dpc/crev/issues/47 to a new thread.

`cargo crev <verb> <obj> <args>` seems to work quite well.

**Edit**: I'll be updating this list. Not all implemented yet.

```
cargo crev
  new
    id
  change
    id
    readme
  review <pkg> <version>
  trust <ids>
  push
  pull
  fetch
    url <url>
    trusted
    all
  query
    id
      current [--urls]
      own [--urls]
      trusted  [--urls]
      distrusted [--urls]
      all [--urls]
    review  [--by <id>] [--trusted] [--distrusted] <pkg> <version>  
    package
      outdated [--trusted]

...
```

**Comment by rffrancon** [comment]
That looks really good!

Just to be clear, how does this work with `help`? Is it just another verb? Would `cargo crev help id` give a list of verbs which can be used with `id`?

Here's an example of verb-noun with that sort of `help`: https://github.com/fnproject/cli/wiki/CLI-Proposal:--verb--noun--structure

**Comment by dpc** [comment]
@rffrancon I'm relying on `help` provided by `structopt`, and it's good enough IMO, for now. If there's a room for improvement, it can be improved later. :)

**Comment by rffrancon** [comment]
Sounds good!

**Comment by dpc** [comment]
It's done. We can revise in the future.
