### ISSUE TITLE
Implement `cargo crev fetch all`.

### ISSUE THREAD

**Issue by dpc** [dpc/crev#55]

**Comment by dpc** [comment]
I think we should eventually improve on it (explained in #65), but a bunch of it was implemented by @rffrancon . Let's keep this open though.

**Comment by rffrancon** [comment]
From @dpc in PR #65 :
> We should first traverse all git repos and update them (remembering which one we updated), then we should load everything into trustdb and update/fetch urls that we haven't yet, and do it recursively until we have no url left.

**Comment by dpc** [comment]
Done 08145c4de5c850621928f4fec7eded3419715a85
