### ISSUE TITLE
cargo crev push tries to use ssh, instead of https

### ISSUE THREAD

**Issue by bjorn3** [dpc/crev#64]
```bash
$ cargo crev push
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dpc** [comment]
Don't everyone use ssh to push to github? Crev will automatically set it. Should it be optional?

**Comment by Dylan-DPC** [comment]
SSH is recommended but people still use HTTPS so i feel it is good to give the user an option to use https if needed (through a flag).

**Comment by dpc** [comment]
Flag is not discoverable - especially for new users. We should probably just print a message that we set the push URL to git url X and you can set it to https with command Y.

**Comment by Ixrec** [comment]
Just as an anecdote, where I work we have to use ssh to hit our Github Enterprise instance from certain machines, and we have to use https to hit it from other machines. It's simply not up to us which protocol gets used. I've never understood why exactly, but obviously that means we'd need an option to manually switch protocols, regardless of what the default is.

**Comment by dpc** [comment]
Note: you can always change the settings with `cargo crev git ...` so this is just a matter of sensible defaults and initial UX.

**Comment by rffrancon** [comment]
Github recommends cloning with HTTPS: https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended

**Comment by rffrancon** [comment]
I think it could be reasonable to attempt to push using a SSH remote URL. If the attempt fails, then switch to pushing with HTTPS remote URL.

**Comment by dpc** [comment]
Anyone can use `cargo crev git remote set-url origin https://github.com/user/repo.git` to change the url at any time, similarly to a normal git repo.

@rffrancon We do clone everything using https. But for pushing `git` is more secure and recommended.

**Comment by bjorn3** [comment]
> Anyone can use cargo crev git remote set-url origin https://github.com/user/repo.git to change the url at any time, similarly to a normal git repo.

Thanks for pointing me at that subcommand.

**Comment by tillarnold** [comment]
In case someone has the same issue: the command to setup pushing with https now appears to be
`cargo crev repo git remote set-url origin https://github.com/user/repo.git`
