### ISSUE TITLE
Discuss security-biased `rating` scale

### ISSUE THREAD

**Issue by Moongoodboy-K** [dpc/crev#67]
This is an alternative to adding rating categories (i.e. separate ratings for `security`, `performance`, `compliance`, `ux`, etc) or adding a tag system.

Pros: keeps `rating` simple (this was a concern of @dpc's)
Cons: not as flexible or expressive

It turns `rating` into a sort of hybrid of _security_ and _overall_ ratings. The meanings go something like this:

* `strong` => This is good code in all respects .
* `positive` => This is, overall, good code. There may be minor issues (but they have no impact on security).
* `neutral` => ?
* `negative` => This is bad code. It has many or severe _non-security_ issues: I recommend against using it.
* `dangerous` => This code has reckless use of `unsafe`, severe security vulnerabilities, or is outright malicious.

The scale is intentionally skewed in favor of caring about security more than other aspects of code. This reflects my (limited—I only heard about it today) understanding of what `crev` is supposed to be. (It also aligns well with the use of the word _dangerous_, IMO—if code has significant vulnerabilities, it is `dangerous`, period.)

(This came out of an idea I had on IRC just now. Please discuss, debate, and bikeshed :D )

**Comment by dpc** [comment]
@Moongoodboy-K That's how things are currently supposed to work. I'm not sure if I missed the twist, or we just totally agree.

Documents here https://github.com/dpc/crev/tree/master/crev-lib/rc/doc should be updated to explain what each value is supposed to mean.

**Comment by dpc** [comment]
@Moongoodboy-K Please take a lookg at the files that I've just edited.

**Comment by Moongoodboy-K** [comment]
> @Moongoodboy-K That's how things are currently supposed to work. I'm not sure if I missed the twist, or we just totally agree.

I think we just agree! I saw names for the places on the scale, but I didn't see descriptions, so I came up with these semantics. I think that if I ended up at the same ideas that you had, just based on reading the names, that's a good sign! :)

**Comment by dpc** [comment]
I'm closing then, since there's nothing actionable, Anyone: feel free keep thinking about it here, or on gitter channel. :)
