### ISSUE TITLE
Idea: "retweet a proof".

### ISSUE THREAD

**Issue by dpc** [dpc/crev#71]
It would work in a similar way to how "retweeting" works on Twitter. If you find an important review proof, you can "re-broadcast" it, by creating your own Review Proof, with the same content, and indicating that it is a copy of someone-else's review, that you find trustworthy and important (in comment, or in a more structured way?).

**Comment by rffrancon** [comment]
Great idea. Nodes in the network (users in the trust network) should be able to help other nodes identify valuable nodes.

**Comment by dpc** [comment]
I'm going to put this one on hold. It seems laborious, and if someone was doing good job reviewing stuff, it's better to just give them trust, even if `low` level. That would make it easy to discover their whole ID, not just one review.
