### ISSUE TITLE
Error: argonautica::Error { kind: argonautica::ErrorKind::PasswordTooShortError, display: "Password too short. Length in bytes must be greater than 0" }

### ISSUE THREAD

**Issue by vi** [dpc/crev#72]
It fails to create new crev id without a passphrase.

Passphrase should be optional and changeable after creation, like with SSH/GPG keys.

Also only the `display` field should probably be displayed in error message.

**Comment by dpc** [comment]
Yes, the error handling is very crude ATM.

**Comment by dpc** [comment]
I don't think I agree that id should work without a passphrase, so I'm not planing to change it. The error message is better now, so I'm closing.
