### ISSUE TITLE
Idea: delta reviews

### ISSUE THREAD

**Issue by vi** [dpc/crev#74]
Doing something like `cargo crev review somecrate 0.2.3..0.2.10`, recording the fact that only difference between versions is reviewed. Combined with a review for version `0.2.3`, it should give equivalent of having `0.2.10` fully reviewed.

**Comment by dpc** [comment]
I would very much would like to have a command that displays a diff between versions (as in: downloads older version and diffs with the current one). Possibly the "old version" could be attempted to be automatically auto-detected, by looking for a last version that was reviewed by same ID, or one of the trusted IDs.


I'm not sure how important it is to record that in the review itself. After all, reviewer is responsible for their reviews, and how exactly they do it, is irrelevant to people that are going to use such review.

**Comment by vi** [comment]
I mean ability to record the fact that review is partial both time-wise (not a snapshot was reviewed, but changes between versions) and file-wise (not all files were considered).

My model is any review efforts, no matter how small, can be stored in some meaningful way.

**Comment by bwbroersma** [comment]
See https://github.com/dpc/crev/issues/104#issuecomment-451621719:
>  I think reviews are only really meaningful if you understand/reviewed the complete crate, independent seemingly harmless partial reviewed commits/versions can create a malicious update in the end.

**Comment by dpc** [comment]
Yeah, the differential review create inherent security issues, and if they are to be supported, they should probaby be restricted to reviews of a diff from a previous version reviewed by the same Id.

**Comment by dpc** [comment]
Closing for #173
