### ISSUE TITLE
Am I supposed to fork dpc/crev-proofs repository to bootstrap crev?

### ISSUE THREAD

**Issue by vi** [dpc/crev#75]
Either way it should be mentioned in README of this repository (i.e. "fork this repository before `cargo crev new id`" or "don't fork this repository, create your own source").

**Comment by dpc** [comment]
I am not sure if we should modify proof repos README's automatically. In a sense it would be nice, but:

* users give an existing repo url, which typically will have an autogenerated README.
* we don't want accidentally overwrite user's README
* what if we change anything in crev UI, and the instructions will become stale everywhere.

**Comment by vi** [comment]
It asks an  "URL to a repository", not a "URL to an empty repository". I assumed that repository must be specially prepared.

Also if repositories are connected with fork/source relationship on Github, it may be easier to discover reviewers that just review things and don't advertise the fact explicitly.

**Comment by dpc** [comment]
I've got an idea. I'll auto-generate `README_USING_THIS_REPO.md` in every proof repo. See https://github.com/dpc/crev-proofs-test .

**Comment by dpc** [comment]
> It asks "URL to a repository", not "URL to an empty repository". I assumed that repository must be specially prepared.

Every user is supposed to create an empty repository for themselves. But this is a good feedback. I'll see into wording of it.

**Comment by dpc** [comment]
Sorry, but I can't write down every single way new users can get confused about what to do. Most people will not read it anyway, and I am putting gitter link everywhere, so users can just ask for help.

**Comment by dpc** [comment]
https://github.com/dpc/crev/wiki/Proof-Repository

**Comment by vi** [comment]
This link should be displayed by `cargo crev new id`, in "enter your username or URL" prompt.

**Comment by dpc** [comment]
c2b1c48f588ff7d0c0761eae1b7334db798aa021

**Comment by dpc** [comment]
I've published a new version on crates.io to help new users. Thanks!

**Comment by Dylan-DPC** [comment]
I have started writing integration tests which create a new folder temporarily  using a crate called [ephemeral](https://github.com/Dylan-DPC/ephemeral) I wrote for the same purpose. We can abstract it out or use it as part of a command so you can generate a project on the fly to test it.

**Comment by dpc** [comment]
Yeah, some integration tests would be great to have @Dylan-DPC . Let's move this to a different issue / discuss on gitter.
