### ISSUE TITLE
Better error messages when locked id password was wrong.

### ISSUE THREAD

**Issue by dpc** [dpc/crev#8]

**Comment by rffrancon** [comment]
@dpc Are you certain the password should be requested in a loop? As a counter example, provided an incorrect password, Git does not re-request the password. It just fails. Provided no work is lost (ensure password requested before work done), it seems cleaner just to end the program.

**Comment by dpc** [comment]
The way I think about it: What's the point of failing? If the user wanted to perform certain operation, and entered a wrong password, most probably it was just a typo etc. and they will want to try again. I assume most users know how to press `Ctrl+C` or `Ctrl+D` to terminate the process.

**Comment by rffrancon** [comment]
You've convinced me, that makes sense.

Should the passphrase closure function be passed all the way down the stack to `local.to_unlocked(...)`? I think that looping for the correct password would be simplest at that point.

**Comment by dpc** [comment]
@rffrancon I guess. I mean - it can easily be changed later, so no need to worry about it too much.

Please create some

`pub type PassphraseFn = ` alias, like in `rdedup`, propagate it where it makes sense, and that's the bulk of it. Make sure to rebase, since I did some refactors recently.

**Comment by Dylan-DPC** [comment]
@rffrancon yep.
