### ISSUE TITLE
File in use by another process

### ISSUE THREAD

**Issue by ThomasdenH** [dpc/crev#93]
When using `cargo crev review`, an error occurs. This probably only happens on Windows. [I have managed to track down the line.](https://github.com/dpc/crev/blob/master/cargo-crev/src/main.rs#L120)

The error I get is
`Error: Os { code: 32, kind: Other, message: "Het proces heeft geen toegang tot het bestand omdat het door een ander\r\nproces wordt gebruikt." }`

which translates to
`Error: Os { code: 32, kind: Other, message: "The process does not have access to the file because it is in use by another process." }`

**Comment by ThomasdenH** [comment]
Turns out I probably misused `cargo crev` here. I did the following:

`git clone git@github.com:ThomasdenH/iban_validate.git`
`cd iban_validate`
`cargo crev review iban_validate`

Still, if this is not the correct way of using this tool there should probably be a warning.

**Comment by dpc** [comment]
Yeah. That's definitely not how it's supposed be used. Right now, to review your crate you will have to create a dummy project with your package as a dependency. Though I'll investigate later what exactly happened here. I think the review function does not ignore cwd packages like verify does and then tried to mess with your project.

**Comment by dpc** [comment]
Fixed.
