### ISSUE TITLE
Mark crates with custom build, `unsafe` (and other stuff worth reviewing)

### ISSUE THREAD

**Issue by dpc** [dpc/crev#94]
* https://docs.rs/cargo/0.32.0/cargo/core/package/struct.Package.html#method.has_custom_build
* For `unsafe` we could use a quick recursive grep, maybe?
* would be nice to integrate some existing safety scanning tool for Rust?

**Comment by ThomasdenH** [comment]
Detecting `unsafe` will be difficult. We'd need a full fledged parser to correctly ignore commented out code for example.

**Comment by dpc** [comment]
Nothing ATM. I'm postponing to 0.4

**Comment by dpc** [comment]
`unsafe` via `cargo-geiger` is done. custom build is a flag. All done.
