### ISSUE TITLE
Reviewing own crate

### ISSUE THREAD

**Issue by ThomasdenH** [dpc/crev#97]
It is probably not desirable to extract owner information from `crates.io`, instead this could just be a claim made in a crate review. This would make it independent of the package manager used.

It would still be useful to have an ownership claim. If a package is written by someone you trust, you can use their 'I own this crate'-review to trust the crate a bit more. Normally, the author will be very familiar with their crate and have reviewed it before publishing. I think it would be good if there was one command you could run after publishing a crate that would create a default ownership review for you and publish it.

**Comment by dpc** [comment]
I guess that's all about it. Fell free to comment/reopen if needed.
